### ISSUE TITLE
Create Tags

### ISSUE THREAD

**Issue by UniversalTraveller** [UniversalTraveller/capstone-project#10]
# Value Proposition

**As a** user
**I want to** be able to create my own tags
**So that** I have a set of tags that matches the topics of my subscribed podcasts.

# Description

![Image](https://user-images.githubusercontent.com/59486612/185923659-d866e5b3-525a-44cf-878d-bd3ca5bf56fe.png)

# Acceptance Criteria

- [ ] Input gets separated into different tags by comma.
- [ ] Surrounding spaces get snipped.
- [ ] Tags may contain spaces.
- [ ] After pressing the submit button, the user stays on the page.
- [ ] After pressing the submit button, the tags the user entered are shown in the list of available tags.

# Tasks

- [ ] Create a component for the create tags form.
- [ ] Process the input.
- [ ] Write logic to add the new tags to the array of tags.
- [ ] Add submit tags form to storybook.
- [ ] Write tests.

# Complexity

M
