### ISSUE TITLE
Add Podcast Images

### ISSUE THREAD

**Issue by UniversalTraveller** [UniversalTraveller/capstone-project#12]
# Value Proposition

**As a** user
**I want to** see the image of each podcast in podcast view
**So that** I can easily recognize podcasts.

# Description

![Image](https://user-images.githubusercontent.com/59486612/186194015-c999c241-b6b6-4662-a2f0-3cdcad6284bf.png)

# Acceptance Criteria

- [ ] When a podcast has no image, a placeholder is visible.
- [ ] Podcast images are part of the clickable area that opens episode view.

# Tasks

- [ ] Get the image URL when parsing the feed.
- [ ] Include the images when rendering the podcast list.
- [ ] Add a placeholder image to public folder.

# Complexity

S
