### ISSUE TITLE
Add Header to Episodes View

### ISSUE THREAD

**Issue by UniversalTraveller** [UniversalTraveller/capstone-project#13]
# Value Proposition

**As a** user
**I want to** have a header in episodes view
**So that** I know which podcast's episodes I am looking at.

# Description

![Image](https://user-images.githubusercontent.com/59486612/186194613-8040a569-fe0b-49f8-9241-4b9aaebc7107.png)

# Acceptance Criteria

- [x] The header should scroll together with the episodes.

# Tasks

- [x] Create header component.
- [x] Minimal styling for header component.
- [x] Add component to storybook.
- [x] Write test for component.

Storybook entry for this component is a different user story: https://github.com/UniversalTraveller/capstone-project/issues/30

# Complexity

S
