### ISSUE TITLE
Fix Time in Seconds

### ISSUE THREAD

**Issue by UniversalTraveller** [UniversalTraveller/capstone-project#17]
# Value Proposition

**As a** user
**I want to** see the duration of an episode properly formatted
**So that** I don't have to guess what a number like "3495" might mean.

# Description

Some podcast feeds like https://wochendaemmerung.de/feed/mp3/ or https://sternengeschichten.podigee.io/rssfeed give the time in seconds instead of the format HH:MM:SS. The podcast player should check for that and convert if necessary.

# Acceptance Criteria

- [ ] The display episodes component should show the episode's duration in the format HH:MM:SS for https://sternengeschichten.podigee.io/rssfeed.
- [ ] The player component should show the episode's duration in the format HH:MM:SS for https://sternengeschichten.podigee.io/rssfeed.

# Tasks

- [ ] Write a utility that checks episode duration format and converts it if necessary.
- [ ] Add this utility to the player component.
- [ ] Add this utility to the display episodes component.

# Complexity

S

**Comment by RobertBReich** [comment]
Hi Andreas,
looks good. 👍 

cheers
R.
