### ISSUE TITLE
Tests for Add Podcast Component

### ISSUE THREAD

**Issue by UniversalTraveller** [UniversalTraveller/capstone-project#19]
# Value Proposition

**As a** developer
**I want to** test whether adding podcasts works as intended
**So that** I can be sure that this crucial part of the app doesn't fail.

# Description

The component for adding podcasts runs some checks on the input and loads a podcast if everything is fine. Test are necessary for the correct execution of these checks and for loading the podcast.

# Acceptance Criteria

- [] A test should check if input that is not a URL leads to an error.
- [] Another test should check if a URL that's not a proper podcast feed leads to an error.
- [] Finally, when the input is a proper podcast feed, that feed should be loaded in the app.

# Tasks

- [ ] Write test for not a URL.
- [ ] Write test for wrong URL.
- [ ] Write test for loading of podcast.

# Complexity

M

**Comment by ckskr** [comment]
That looks good :)

**Comment by UniversalTraveller** [comment]
Thanks for reviewing, Claudia!
