### ISSUE TITLE
Display Episodes

### ISSUE THREAD

**Issue by UniversalTraveller** [UniversalTraveller/capstone-project#2]
# Value Proposition

As a user I want to see a list of three episodes so that I can load one of them in the player.

# Description

Scribble / design or text

# Acceptance Criteria

- [ ] A list with three episodes must be visible on the screen.
- [ ] For each episode the title of the podcast and the title of the episode are shown. 
- [ ] Clicking on one opens the episode in the player at the bottom of the screen.
- [ ] Clicking on another episode replaces the episode in the player.

# Tasks

- [ ] Create an array of objects for the podcast episodes.
- [ ] Each episode object contains an unique ID (nanoid), the episodes URL, a title and the name of the podcast.
- [ ] Create a component for episodes list.
- [ ] Map through the episodes to display them in the list.

# Complexity

S

**Comment by ahohnsen** [comment]
Hey Andreas,

Nicely done! I have a few suggestions:

I would recommend to stick to the format of the value proposition:

**As a** user
**I want to** see an episode list 
**so that** I can get an overview about what's there.

- Your scribble should contain real content and no placeholder text (e.g. Episode One Title).
- In your acceptance criteria you could be a bit more specific: _A list of episodes (at least three) must be visible on the screen._ "At least three" is not so specific. As well, it would be good to mention if your page is going to be scrollable.
- All the things which are visible in your scribble do not need to be described in your acceptance criteria e.g. For each episode, the title of the podcast and the title of the episode are shown.

**Comment by UniversalTraveller** [comment]
Hi Andrea,

thanks a lot for your feedback! I changed the user story accordingly.
