### ISSUE TITLE
Restructure Navigation

### ISSUE THREAD

**Issue by UniversalTraveller** [UniversalTraveller/capstone-project#28]
# Value Proposition

**As a** user
**I want to** I want to have all controls that affect a single podcast on this podcast's details page
**So that** I can easily find them.

# Description

![Image](https://user-images.githubusercontent.com/59486612/188330643-35f2e744-7c83-400a-a417-dc581fdc519a.png)

# Acceptance Criteria

- [ ] A new podcast detail page replaces episodes view.
- [ ] The podcasts ID is in the URL so that every podcast has its own detail page.
- [ ] No "Edit Tags" button in the podcast list any more.
- [ ] No "Episodes" nutton in the header navigation any more.

# Tasks

- [ ] Change mechanism for podcast selection form global state to routing.
- [ ] Move buttons around.

# Complexity

M

**Comment by j-eick** [comment]
I first thought that the right side is an additional page that shows up, after clicking a button.
Is the left side the episodes view, which will be replaced by the right side? The title of the left side says "podcast list", so I'm a little confused.

> A new podcast details page replaces episodes view.

As a reader I'd like to know what you mean by "episodes view". You know it, but I don't. Adding that one as additional screenshot would be helpful.

> Move buttons around.

This sounds arbitrary. 
Suggestion: Repositioning buttons.
