### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by UniversalTraveller** [UniversalTraveller/capstone-project#29]
# Value Proposition

**As a** user
**I want to** have a good looking and visually well structured app
**So that** it's easy and fun to listen to podcasts.

# Description

The whole app should look less like a wireframe and more like polished software.

# Acceptance Criteria

- [ ] Distinctive fonts are used.
- [ ] The app has a unique and fitting color scheme.
- [ ] The app looks like from one mold.

# Tasks

- [ ] Use styled components theming.
- [ ] Select nice fonts and install them locally.
- [ ] Decide for a good-looking color palette.
- [ ] Make sure that margins, border-radius, box-shadow etc. are more or less the same throughout the app.
- [ ] Perhaps use SVGs for buttons.

# Complexity

L
