### ISSUE TITLE
Show Episode details

### ISSUE THREAD

**Issue by UniversalTraveller** [UniversalTraveller/capstone-project#3]
# Value Proposition

**As a** user
**I want to** click on an episode to open it
**so that** I can get more detailed information about it.

# Description

![Image](https://user-images.githubusercontent.com/59486612/184635174-b0d42a49-afa5-4b24-a86f-4ac53e14ae30.png)

# Acceptance Criteria

- [ ] A click on an episode in the episode list opens a detail view.
- [ ] The detail view contains the show notes, but shortened to three lines.

# Tasks

- [ ] Add a component for the player/detail view.
- [ ] Add an object for the selected episode in a zustand store.
- [ ] The object should contain the title of the episode, its URL, its length, the publishing date, the show notes, and the podcast (name/artist).
- [ ] Add the player component to stylebook.
- [ ] Test whether the beginning of the show notes is displayed.

# Complexity

M

**Comment by aclaes** [comment]
Hi Andreas,

the promised value for the user cannot be fulfilled. There is no feature to start listener yet.

Therefore this user story is incomplete. It won't add any value for the user.

I think your first user story should be concerned about rendering an episode list of a podcast.

This could be the second user story to select a single episode and see details (like the length). The next one could be the audio player.

Also you should not spend much time on UI styling in the beginning. The "bottom fixed" position should not be part of an early user story yet.

**Comment by ahohnsen** [comment]
Hey Andreas,

Please stick to the given format for the value proposition:

**As a** user
**I want to** click on an episode to open it 
**so that** I can get more detailed information about it.

It would be nice if the scribble would contain the whole screen and not just a part of it. With the scribble you have added it is not clear if the detailed view opens as an overlay or if it just pushes the rest of the list further down. 🤔

>  A click on an episode in the episode list opens a detail view.
The detail view contains the show notes, but shortened to three lines.

How can the detailed view be closed? On a second click or will there be a close-button? And how can the user see the whole description? I would assume that I can see everything in a detailed view 🙂
