### ISSUE TITLE
Storybook Entry for Podcast Header Component

### ISSUE THREAD

**Issue by UniversalTraveller** [UniversalTraveller/capstone-project#30]
# Value Proposition

**As a** developer
**I want to** have the podcast header component in storybook
**So that** I can gain a better overview about all my app's components.

# Description

The isolated podcast header is visible in Storybook.

# Acceptance Criteria

- [ ] There is an entry for `PodcastHeader` in storybook.
- [ ] The component should look the same as in the app.

# Tasks

- [ ] Add `PodcastHeader` to Storybook.
- [ ] Research how to use images from exernal sources in Storybook.

# Complexity

S
