### ISSUE TITLE
Fix broken Tests

### ISSUE THREAD

**Issue by UniversalTraveller** [UniversalTraveller/capstone-project#33]
# Value Proposition

**As a** developer
**I want to** see that the app passes all my tests
**So that** I know everything works as is should.

# Description

Switching to Next.js Router for podcast selection broke some tests, because they got the selected podcast as props or via global state before. There must be some way to mock a URL path in Jest.

# Acceptance Criteria

- [ ] Testing PodcastHeader component works.
- [ ] Testing DisplayEpisodes component works.
- [ ] Testing DeletePodcast component works.

# Tasks

(for developers team)

- [ ] Wait until somebody answered here: https://github.com/orgs/neuefische/discussions/142
- [ ] Fix the tests.
- [ ] Delete the `skip`-marker in the tests.

# Complexity

M
