### ISSUE TITLE
Play Episode

### ISSUE THREAD

**Issue by UniversalTraveller** [UniversalTraveller/capstone-project#4]
# Value Proposition

As a user, I want to play the selected episode by pressing the play button, so that I can listen to exciting podcasts.

# Description

![Image](https://user-images.githubusercontent.com/59486612/184612032-33dee469-20f9-4f37-8543-ef64936586ee.png)

# Acceptance Criteria

- [ ] There should be a play button in the player.
- [ ] Pressing the play button starts to play the selected episode.
- [ ] The play button changes to a stop button when pressed.
- [ ] Pressing the stop button stops playback.
- [ ] Pressing the stop button changes it to a play button.
- [ ] Pressing the play button again plays the episode from the beginning again.

# Tasks

- [ ] Create a component for the play button.
- [ ] Create a styled component for the play button.
- [ ] Add some very basic styling for the play button.
- [ ] Give the selected episode two states: "playing" and "stopped".
- [ ] Create a modifier "playing" for the play button.
- [ ] Add audio functionality.
- [ ] Add the play button to stylebook.
- [ ] Test for changing states "playing" and "stopped".

# Complexity

M

**Comment by RobertBReich** [comment]
Hi Andreas,

looks good 👍

**Comment by ahohnsen** [comment]
Hey Andreas,

Please see my comment on your previous user story regarding the format of the value proposition and the scribble 🙂 As well, it would be nice if you would use real content in the scribble and no placeholder text (e.g. selected episode, podcast, artist)

**Comment by UniversalTraveller** [comment]
Hi Petros,

thanks for your feedback! Exactly, that's an idea for a future feature.
