### ISSUE TITLE
Add Podcast

### ISSUE THREAD

**Issue by UniversalTraveller** [UniversalTraveller/capstone-project#6]
# Value Proposition

**As a** user
**I want to** be able to add a new podcast
**So that** I have access to all the publicly available podcasts out there.

# Description

![Image](https://user-images.githubusercontent.com/59486612/185496507-76d137a0-2ad5-4654-ba57-588bd5867fef.png)

# Acceptance Criteria

- [ ] There must be an add button in podcast view.
- [ ] Clicking on the add button opens a form.
- [ ] The form has an input button and a submit button.
- [ ] Clicking on the submit button shows a result message.
- [ ] If the input is no valid podcast feed, the result message is an error message.
- [ ] If the input is a valid podcast feed, the result message says: "Added new podcast: [podcast name]".
- [ ] If the input is a valid podcast feed, the podcast gets added.
- [ ] Clicking on the new podcast will send the user to this podcasts episode view.

# Tasks

- [ ] Add an add button to podcast view.
- [ ] Create a form component.
- [ ] Add form component to stylebook.
- [ ] Create a result message component.
- [ ] Add result message component to stylebook. 
- [ ] Validate the input.
- [ ] Fetch and parse RSS feed.
- [ ] Create a new podcast object.
- [ ] Write tests.

# Complexity

XL
