### ISSUE TITLE
Delete a podcast

### ISSUE THREAD

**Issue by UniversalTraveller** [UniversalTraveller/capstone-project#7]
# Value Proposition

**As a** user
**I want to** be able to delete a podcast
**So that** podcasts I don't listen too don't clutter my feed.

# Description

![Image](https://user-images.githubusercontent.com/59486612/185877798-469e9316-2859-4e54-a65a-5cb61bb95d9c.png)

# Acceptance Criteria

- [ ] There must be a delete button in episodes view.
- [ ] Clicking on the delete button opens a confirmation window.
- [ ] When the user confirms deletion, the podcast object with all its episodes gets removed.
- [ ] When the user cancels deletion, nothing happens and the confirmation window closes.
- [ ] After deletion of a podcast, the confirmation window closes and the user lands in podcast view.

# Tasks

- [ ] Add a delete button to episodes view.
- [ ] Create confirmation window component.
- [ ] Delete Podcast Object.
- [ ] Write tests.

# Complexity

S
