### ISSUE TITLE
Edit Tags

### ISSUE THREAD

**Issue by UniversalTraveller** [UniversalTraveller/capstone-project#8]
# Value Proposition

**As a** user
**I want to** be able to add tags to and remove them from a podcast
**So that** I am able to categorize the podcasts I subscribed to.

# Description

![Image](https://user-images.githubusercontent.com/59486612/185893767-4e6a7e7f-a205-4136-9ddb-b02c64b4792e.png)

# Acceptance Criteria

- [ ] In podcast view, every podcast has an edit button.
- [ ] Clicking on the edit button opens edit tags view.
- [ ] Tags can be added and removed by dragging them on the screen.
- [ ] Clicking on the done button closes edit tags view and the user returns to podcast view.

# Tasks

- [ ] Create an array with tags, every tag has a unique ID.
- [ ] Create a mechanism for associating tags (by ID) with podcasts.
- [ ] Research how to implement drag and drop functionality.
- [ ] Create a component for edit tags view.
- [ ] Create a component for tag list.
- [ ] Add components to storybook.
- [ ] Write tests.

# Complexity

L
